POST http://localhost:5000/api/auth/resgister
Content-Type: application/json

{
    "username": "oanhtran",
    "password": "oanhtran1"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "oanhtran",
    "password": "oanhtran1"
}