POST http://localhost:5000/api/auth/resgister
Content-Type: application/json

{
    "username": "oanhtran",
    "password": "oanhtran1"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "oanhtran",
    "password": "oanhtran1"
}

###

GET http://localhost:5000/api/products

###
GET http://localhost:5000/api/products/616019ff49fada06247ba84b